name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    strategy:
      matrix:
        target:
          - linux-amd64
          - linux-arm64
          - darwin-amd64
          - darwin-arm64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.1.0
    with:
      go-version: "1.26"
      config-file: .slsa-goreleaser-${{ matrix.target }}.yml
      upload-assets: true
